title: Needlessly Deep
email: needlesslydeep@gmail.com
description: Serious research for silly questions.
baseurl: ""
url: "https://needlesslydeep.github.io"

twitter_username: NeedlesslyDeep
github_username: needlesslydeep

plugins:
  - jekyll-feed

collections:
  papers:
    output: true
    permalink: /papers/:title/